# Generated by Django 2.2.2 on 2019-06-11 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('main', '0002_auto_20190611_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='curse',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
    ]
