# Generated by Django 2.2.2 on 2019-06-11 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190611_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curse',
            old_name='date_start',
            new_name='add_date',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='date_release',
            new_name='date_time_release',
        ),
        migrations.AddField(
            model_name='curse',
            name='date_time_release',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
