# Generated by Django 2.2.2 on 2019-06-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='biography',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
